/**
 * ReportI18n — 服务端报告国际化模块
 * i18n-ui-report.md §3.3 + §4
 *
 * 按 locale 提供报告渲染所需的所有静态标签：章节标题、表头、
 * 风险等级说明、页脚、免责声明等。
 *
 * 支持的 locale：zh-CN（默认）、en-US
 * 未知 locale 自动回退到 zh-CN。
 */

import type { GapAnalysisReport } from '@risk-agent/core';

// ─── 标签接口 ─────────────────────────────────────────────────────────────────

export interface ReportLabels {
  title: string;
  business: string;
  score: string;
  generatedAt: string;
  locale: string;
  coverage: string;
  criticalGaps: string;
  allGaps: string;
  suggestions: string;
  none: string;
  scenario: string;
  coveragePercent: string;
  coveredRules: string;
  ruleType: string;
  severity: {
    critical: string;
    high: string;
    medium: string;
    low: string;
  };
  gapTitle: string;
  gapDescription: string;
  footer: string;
  disclaimer: string;
  metadata: {
    reportId: string;
    sessionId: string;
    version: string;
    engine: string;
  };
}

// ─── 内置标签字典（从模板文件同步维护，避免 runtime fs.readFile） ─────────────

const ZH_CN_LABELS: ReportLabels = {
  title: '风控缺口分析报告',
  business: '业务对象',
  score: '总体得分',
  generatedAt: '生成时间',
  locale: '报告语言',
  coverage: '规则覆盖矩阵',
  criticalGaps: '关键缺口',
  allGaps: '全部缺口',
  suggestions: '优化建议',
  none: '（无）',
  scenario: '场景',
  coveragePercent: '覆盖率',
  coveredRules: '已覆盖规则',
  ruleType: '规则类型',
  severity: { critical: '严重', high: '高风险', medium: '中风险', low: '低风险' },
  gapTitle: '缺口标题',
  gapDescription: '说明',
  footer: '本报告由 Risk Agent 自动生成，仅供参考。风控规则覆盖情况可能受数据时效性影响，请结合实际业务场景进行解读。',
  disclaimer: '本报告不构成任何法律或合规意见。',
  metadata: { reportId: '报告 ID', sessionId: '会话 ID', version: '版本', engine: '分析引擎' },
};

const EN_US_LABELS: ReportLabels = {
  title: 'Risk Gap Analysis Report',
  business: 'Business',
  score: 'Overall Score',
  generatedAt: 'Generated At',
  locale: 'Report Language',
  coverage: 'Rule Coverage Matrix',
  criticalGaps: 'Critical Gaps',
  allGaps: 'All Gaps',
  suggestions: 'Suggestions',
  none: '(none)',
  scenario: 'Scenario',
  coveragePercent: 'Coverage',
  coveredRules: 'Covered Rules',
  ruleType: 'Rule Type',
  severity: { critical: 'Critical', high: 'High', medium: 'Medium', low: 'Low' },
  gapTitle: 'Gap Title',
  gapDescription: 'Description',
  footer: 'This report was automatically generated by Risk Agent and is for reference only. Rule coverage may be affected by data timeliness. Please interpret in conjunction with the actual business context.',
  disclaimer: 'This report does not constitute any legal or compliance advice.',
  metadata: { reportId: 'Report ID', sessionId: 'Session ID', version: 'Version', engine: 'Analysis Engine' },
};

const LABEL_MAP: Record<string, ReportLabels> = {
  'zh-CN': ZH_CN_LABELS,
  'zh': ZH_CN_LABELS,
  'en-US': EN_US_LABELS,
  'en': EN_US_LABELS,
};

// ─── 公共 API ─────────────────────────────────────────────────────────────────

/**
 * 根据 locale 获取报告标签。
 * 未知 locale 自动回退到 zh-CN。
 */
export function getReportLabels(locale = 'zh-CN'): ReportLabels {
  return LABEL_MAP[locale] ?? ZH_CN_LABELS;
}

/**
 * 将 GapAnalysisReport 渲染为 Markdown。
 * 所有静态文案通过 getReportLabels() 获取，不硬编码语言字符串。
 */
export function renderReportMarkdown(report: GapAnalysisReport, locale = 'zh-CN'): string {
  const t = getReportLabels(locale);
  const lines: string[] = [];

  lines.push(`# ${t.title}`);
  lines.push('');
  lines.push(`- **${t.business}**: ${report.businessName}`);
  lines.push(`- **${t.score}**: ${report.overallScore}`);
  if (report.locale) lines.push(`- **${t.locale}**: ${report.locale}`);
  lines.push('');

  // 覆盖矩阵
  lines.push(`## ${t.coverage}`);
  lines.push('');
  if (report.coverageMatrix.length === 0) {
    lines.push(t.none);
  } else {
    for (const row of report.coverageMatrix) {
      const scenarioLabel = row.scenarioName ?? row.scenarioId;
      const covered = row.coveredRuleIds?.length ?? 0;
      lines.push(`- **${scenarioLabel}**: ${row.coveragePercent}% ${t.coveragePercent} (${covered} ${t.coveredRules})`);
    }
  }
  lines.push('');

  // 关键缺口
  lines.push(`## ${t.criticalGaps}`);
  lines.push('');
  if (report.criticalGaps.length === 0) {
    lines.push(t.none);
  } else {
    for (const g of report.criticalGaps) {
      const sevLabel = t.severity[g.severity as keyof typeof t.severity] ?? g.severity;
      lines.push(`- **[${sevLabel}]** ${g.title}`);
      if (g.description) lines.push(`  ${g.description}`);
    }
  }
  lines.push('');

  // 全部缺口
  lines.push(`## ${t.allGaps}`);
  lines.push('');
  if (report.allGaps.length === 0) {
    lines.push(t.none);
  } else {
    for (const g of report.allGaps) {
      const sevLabel = t.severity[g.severity as keyof typeof t.severity] ?? g.severity;
      lines.push(`- [${sevLabel}] ${g.title}`);
    }
  }
  lines.push('');

  // 优化建议
  lines.push(`## ${t.suggestions}`);
  lines.push('');
  if (!report.suggestions?.length) {
    lines.push(t.none);
  } else {
    for (const s of report.suggestions) {
      lines.push(`- ${s}`);
    }
  }

  // 叙述性文本
  if (report.narrative) {
    lines.push('');
    lines.push(report.narrative);
  }

  // 页脚
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`*${t.footer}*`);
  if (t.disclaimer) lines.push('');
  if (t.disclaimer) lines.push(`> ${t.disclaimer}`);

  return lines.join('\n');
}
