/**
 * 报告模块 API（06-output-reporting.md §6）
 *
 * GET    /api/reports                           — 报告列表
 * GET    /api/reports/compare?r1=:id&r2=:id    — 对比两次报告
 * GET    /api/reports/:id                       — 报告详情（含费用摘要）
 * GET    /api/reports/:id/markdown             — 下载 Markdown
 * GET    /api/reports/:id/export.md            — 下载 Markdown（旧路径保留兼容）
 * GET    /api/reports/:id/html                 — 下载 HTML（美观带样式）
 * DELETE /api/reports/:id                      — 删除报告
 */
import type { FastifyInstance } from 'fastify';
import type { AppContext } from '../index.js';
import { renderReportMarkdown } from '../reports/ReportI18n.js';

// ─── HTML 模板（06-output-reporting.md §2.2）────────────────────────────────

function mdToHtml(md: string): string {
  // 轻量 Markdown → HTML 转换（不引入外部依赖）
  let html = md
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    // 标题
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    // 粗体 / 斜体
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    // 列表（无序）
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    // 段落
    .replace(/\n\n/g, '</p><p>')
    // 水平线
    .replace(/^---$/gm, '<hr>');
  // 包裹 li 标签
  html = html.replace(/(<li>.*<\/li>\n?)+/gs, (m) => `<ul>${m}</ul>`);
  return html;
}

function wrapHtmlReport(body: string, title: string): string {
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<title>${title}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'PingFang SC', 'Helvetica Neue', sans-serif; margin: 0; background: #0f1220; color: #e6e8f2; line-height: 1.6; }
  .container { max-width: 900px; margin: 0 auto; padding: 40px 24px; }
  h1 { font-size: 1.6rem; font-weight: 700; color: #6b8afe; border-bottom: 1px solid #2a3054; padding-bottom: 12px; margin-bottom: 24px; }
  h2 { font-size: 1.1rem; font-weight: 600; color: #c8cce0; margin-top: 32px; margin-bottom: 12px; padding-left: 8px; border-left: 3px solid #6b8afe; }
  h3 { font-size: 0.95rem; font-weight: 600; color: #a8adc0; margin-top: 20px; }
  p { color: #8d92a8; margin: 8px 0; }
  ul { padding-left: 20px; color: #8d92a8; }
  li { margin: 4px 0; }
  strong { color: #e6e8f2; font-weight: 600; }
  hr { border: none; border-top: 1px solid #2a3054; margin: 24px 0; }
  .meta { display: flex; gap: 16px; margin-bottom: 24px; flex-wrap: wrap; }
  .badge { font-size: 0.75rem; padding: 4px 10px; border-radius: 999px; border: 1px solid; font-family: monospace; }
  .badge-blue { color: #6b8afe; border-color: rgba(107,138,254,0.3); background: rgba(107,138,254,0.1); }
  .badge-green { color: #30d158; border-color: rgba(48,209,88,0.3); background: rgba(48,209,88,0.1); }
  .badge-yellow { color: #ffba08; border-color: rgba(255,186,8,0.3); background: rgba(255,186,8,0.1); }
  .badge-red { color: #ff5a5f; border-color: rgba(255,90,95,0.3); background: rgba(255,90,95,0.1); }
  .footer { margin-top: 48px; border-top: 1px solid #2a3054; padding-top: 16px; font-size: 0.75rem; color: #5d6380; }
</style>
</head>
<body>
<div class="container">
${body}
<div class="footer">Generated by Risk Agent · ${new Date().toISOString()}</div>
</div>
</body>
</html>`;
}

// ─── 对比摘要（§6 compare）──────────────────────────────────────────────────

function compareReports(a: any, b: any) {
  const gapA = (a.allGaps ?? a.gaps ?? []);
  const gapB = (b.allGaps ?? b.gaps ?? []);
  const countBySev = (gaps: any[]) => ({
    critical: gaps.filter((g) => g.severity === 'critical').length,
    high:     gaps.filter((g) => g.severity === 'high').length,
    medium:   gaps.filter((g) => g.severity === 'medium').length,
    low:      gaps.filter((g) => g.severity === 'low').length,
  });
  const scenariosA = new Set((a.coverageMatrix ?? []).map((r: any) => r.scenarioName ?? r.scenarioId));
  const scenariosB = new Set((b.coverageMatrix ?? []).map((r: any) => r.scenarioName ?? r.scenarioId));
  const newScenarios = [...scenariosB].filter((s) => !scenariosA.has(s));
  const removedScenarios = [...scenariosA].filter((s) => !scenariosB.has(s));
  return {
    reportA: { reportId: a.reportId, businessName: a.businessName, score: a.overallScore, createdAt: a.createdAt, gapCount: gapA.length, bySeverity: countBySev(gapA) },
    reportB: { reportId: b.reportId, businessName: b.businessName, score: b.overallScore, createdAt: b.createdAt, gapCount: gapB.length, bySeverity: countBySev(gapB) },
    scoreDelta: (b.overallScore ?? 0) - (a.overallScore ?? 0),
    gapCountDelta: gapB.length - gapA.length,
    newScenarios,
    removedScenarios,
  };
}

export function registerReportRoutes(app: FastifyInstance, ctx: AppContext): void {
  const store = ctx.storage.getStructuredStore();

  // GET /api/reports — 报告列表
  app.get('/api/reports', async () => {
    const rows = await store.all<any>(
      `SELECT report_id, session_id, business_name, locale, overall_score, created_at FROM gap_reports ORDER BY created_at DESC LIMIT 100`
    );
    return rows.map((r: any) => ({
      reportId:     r.report_id,
      sessionId:    r.session_id,
      businessName: r.business_name,
      locale:       r.locale,
      overallScore: r.overall_score,
      createdAt:    r.created_at
    }));
  });

  // GET /api/reports/compare?r1=:id&r2=:id — 对比两次报告（06-output-reporting.md §6）
  app.get('/api/reports/compare', async (req, reply) => {
    const { r1, r2 } = (req.query ?? {}) as { r1?: string; r2?: string };
    if (!r1 || !r2) return reply.code(400).send({ error: 'r1 and r2 required' });
    const [rowA, rowB] = await Promise.all([
      store.get<any>(`SELECT * FROM gap_reports WHERE report_id=?`, [r1]),
      store.get<any>(`SELECT * FROM gap_reports WHERE report_id=?`, [r2]),
    ]);
    if (!rowA) return reply.code(404).send({ error: 'report_a_not_found' });
    if (!rowB) return reply.code(404).send({ error: 'report_b_not_found' });
    return compareReports(JSON.parse(rowA.payload_json), JSON.parse(rowB.payload_json));
  });

  // GET /api/reports/:id — 报告详情（含费用摘要，06-output-reporting.md §8）
  app.get('/api/reports/:id', async (req, reply) => {
    const { id } = req.params as { id: string };
    const { locale } = (req.query ?? {}) as { locale?: string };
    const row = await store.get<any>(`SELECT * FROM gap_reports WHERE report_id=?`, [id]);
    if (!row) return reply.code(404).send({ error: 'not_found' });
    const report = JSON.parse(row.payload_json);
    if (locale && locale !== report.locale) report.locale = locale;
    // 附加费用摘要（从 session_costs 表）
    const costRow = await store.get<any>(
      `SELECT * FROM session_costs WHERE session_id=? ORDER BY created_at DESC LIMIT 1`,
      [row.session_id]
    ).catch(() => null);
    if (costRow) {
      report.costSummary = {
        totalCostUsd: costRow.total_cost_usd ?? 0,
        totalInputTokens: costRow.total_input_tokens ?? 0,
        totalOutputTokens: costRow.total_output_tokens ?? 0,
        cacheReadTokens: costRow.cache_read_tokens ?? 0,
        totalApiDurationMs: costRow.total_api_duration_ms ?? 0,
        totalToolDurationMs: costRow.total_tool_duration_ms ?? 0,
        modelUsage: costRow.model_usage_json ? JSON.parse(costRow.model_usage_json) : [],
      };
    }
    return report;
  });

  // GET /api/reports/:id/markdown — 下载 Markdown（06-output-reporting.md §6）
  app.get('/api/reports/:id/markdown', async (req, reply) => {
    const { id } = req.params as { id: string };
    const { locale } = (req.query ?? {}) as { locale?: string };
    const row = await store.get<any>(`SELECT * FROM gap_reports WHERE report_id=?`, [id]);
    if (!row) return reply.code(404).send({ error: 'not_found' });
    const report = JSON.parse(row.payload_json);
    const markdown = renderReportMarkdown(report, locale ?? report.locale ?? 'zh-CN');
    reply.header('content-type', 'text/markdown; charset=utf-8');
    reply.header('content-disposition', `attachment; filename="${row.business_name}-report.md"`);
    reply.send(markdown);
  });

  // GET /api/reports/:id/export.md — 旧路径（保留向后兼容）
  app.get('/api/reports/:id/export.md', async (req, reply) => {
    const { id } = req.params as { id: string };
    const { locale } = (req.query ?? {}) as { locale?: string };
    const row = await store.get<any>(`SELECT * FROM gap_reports WHERE report_id=?`, [id]);
    if (!row) return reply.code(404).send({ error: 'not_found' });
    const report = JSON.parse(row.payload_json);
    const markdown = renderReportMarkdown(report, locale ?? report.locale ?? 'zh-CN');
    reply.header('content-type', 'text/markdown; charset=utf-8');
    reply.send(markdown);
  });

  // GET /api/reports/:id/html — 下载 HTML（06-output-reporting.md §2.2）
  app.get('/api/reports/:id/html', async (req, reply) => {
    const { id } = req.params as { id: string };
    const { locale } = (req.query ?? {}) as { locale?: string };
    const row = await store.get<any>(`SELECT * FROM gap_reports WHERE report_id=?`, [id]);
    if (!row) return reply.code(404).send({ error: 'not_found' });
    const report = JSON.parse(row.payload_json);
    const markdown = renderReportMarkdown(report, locale ?? report.locale ?? 'zh-CN');
    const bodyHtml = mdToHtml(markdown);
    const fullHtml = wrapHtmlReport(bodyHtml, `${report.businessName} — Risk Report`);
    reply.header('content-type', 'text/html; charset=utf-8');
    reply.header('content-disposition', `attachment; filename="${row.business_name}-report.html"`);
    reply.send(fullHtml);
  });

  // DELETE /api/reports/:id — 删除报告（06-output-reporting.md §6）
  app.delete('/api/reports/:id', async (req, reply) => {
    const { id } = req.params as { id: string };
    const row = await store.get<any>(`SELECT report_id FROM gap_reports WHERE report_id=?`, [id]);
    if (!row) return reply.code(404).send({ error: 'not_found' });
    await store.run(`DELETE FROM gap_reports WHERE report_id=?`, [id]);
    // 尝试从对象存储删除文件（可能不存在，忽略错误）
    try {
      const objectStore = ctx.storage.getObjectStore();
      await objectStore.delete(`reports/${id}/report.md`).catch(() => {});
      await objectStore.delete(`reports/${id}/report.html`).catch(() => {});
      await objectStore.delete(`reports/${id}/report.json`).catch(() => {});
    } catch { /* 对象存储可能不支持 delete，忽略 */ }
    return reply.code(204).send();
  });
}
